name: build-tasks

on:
  # this is meant to be run on an approved PR branch for convenience
  workflow_dispatch:

# We derive a unique ID here to make sure that we don't get into a situation
# where different runners pick different tags (eg: for builds near midnight, or
# in different time zones).  The manifest job picks the final name.
env:
  tag: ghcr.io/allisonkarlitskaya/tasks
  tmptag: ghcr.io/allisonkarlitskaya/tasks-tmp:${{ github.run_id }}.${{ github.run_attempt }}

jobs:
  build:
    strategy:
      matrix:
        build:
          - label: amd64
            runner: buildjet-2vcpu-ubuntu-2204
          - label: arm64
            runner: buildjet-2vcpu-ubuntu-2204-arm

    runs-on: ${{ matrix.build.runner }}
    timeout-minutes: 10

    steps:
      -
        name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.tmptag }}-${{ matrix.build.label }}
          context: tasks/container
          file: tasks/container/Containerfile

  manifest:
    needs: build

    runs-on: buildjet-2vcpu-ubuntu-2204
    timeout-minutes: 5

    steps:
      - run: podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - run: podman manifest create tasks '${{ env.tmptag }}'-{amd,arm}64
      - run: podman manifest push tasks "${{ env.tag }}:$(date --iso-8601)"
      - run: podman manifest push tasks "${{ env.tag }}:latest"
